#!/bin/sh
# Hiker Full WiFi - Initial Configuration
# Configure dual virtual interfaces and enable services

# First, update firewall zones before deleting lan interface
if [ -f /etc/config/firewall ]; then
	# Find and update existing lan zone
	for i in 0 1 2 3 4 5 6 7 8 9 10; do
		zone_name=$(uci get firewall.@zone[$i].name 2>/dev/null)
		if [ "$zone_name" = "lan" ]; then
			uci set firewall.@zone[$i].network='lanBackup LanPrint'
			uci commit firewall
			break
		fi
	done
fi

# Remove default lan interface (now safe since firewall updated)
uci delete network.lan

# Configure LanBackup (static management IP)
uci set network.lanBackup=interface
uci set network.lanBackup.device='br-lan'
uci set network.lanBackup.proto='static'
uci set network.lanBackup.ipaddr='192.168.100.1'
uci set network.lanBackup.netmask='255.255.255.0'

# Configure LanPrint (DHCP interface)
uci set network.LanPrint=interface
uci set network.LanPrint.device='br-lan'
uci set network.LanPrint.proto='dhcp'

uci commit network

# Configure wireless AP with default SSID
uci set wireless.radio0.country='CN'
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid='Hiker-WiFi'
uci set wireless.default_radio0.encryption='none'
uci set wireless.default_radio0.network='lanBackup'
uci commit wireless

# Enable p910nd service
/etc/init.d/p910nd enable

# Note: wifi reload is not needed in uci-defaults
# The wireless interface will be started automatically after boot

