#!/bin/sh
# Hiker Print - Network Configuration
# Configure dual virtual interfaces: LanBackup (static) + LanPrint (DHCP)

# First, update firewall zones before deleting lan interface
if [ -f /etc/config/firewall ]; then
	# Find and update existing lan zone, delete wan zone
	i=0
	while uci get firewall.@zone[$i] >/dev/null 2>&1; do
		zone_name=$(uci get firewall.@zone[$i].name 2>/dev/null)
		if [ "$zone_name" = "lan" ]; then
			uci set firewall.@zone[$i].network='lanBackup LanPrint'
		elif [ "$zone_name" = "wan" ]; then
			uci delete firewall.@zone[$i]
		fi
		i=$((i + 1))
		[ $i -gt 10 ] && break  # Safety limit
	done
	uci commit firewall
fi

# Remove default lan interface (now safe since firewall updated)
uci delete network.lan

# Configure LanBackup (static management IP)
uci set network.lanBackup=interface
uci set network.lanBackup.device='br-lan'
uci set network.lanBackup.proto='static'
uci set network.lanBackup.ipaddr='192.168.100.1'
uci set network.lanBackup.netmask='255.255.255.0'

# Configure LanPrint (DHCP interface)
uci set network.LanPrint=interface
uci set network.LanPrint.device='br-lan'
uci set network.LanPrint.proto='dhcp'

uci commit network

# Enable p910nd service
/etc/init.d/p910nd enable

