name: Build All Profiles (Auto)

on:
  push:
    branches:
      - main
    paths:
      - 'devices/**'
      - '.github/workflows/build-firmware.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  OPENWRT_REPO: openwrt/openwrt
  OPENWRT_BRANCH: main
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Hiker RT5350 - 4 profiles
          - device: hiker-rt5350
            profile: minimal
            name: "Hiker RT5350 - Minimal"
          - device: hiker-rt5350
            profile: p910nd
            name: "Hiker RT5350 - P910ND"
          - device: hiker-rt5350
            profile: wifi-client
            name: "Hiker RT5350 - WiFi Client"
          - device: hiker-rt5350
            profile: full-wifi
            name: "Hiker RT5350 - Full WiFi"

    name: ${{ matrix.name }}
    
    steps:
      - name: Checkout custom-devices feed
        uses: actions/checkout@v4
        with:
          path: custom-devices

      - name: Initialize environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget \
            python3 python3-minimal libelf-dev ca-certificates curl \
            qemu-utils squashfs-tools
          sudo timedatectl set-timezone "$TZ"

      - name: Clone OpenWrt
        run: |
          git clone --depth 1 https://github.com/${{ env.OPENWRT_REPO }}.git -b ${{ env.OPENWRT_BRANCH }} openwrt
          cd openwrt
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          echo "DEVICE_PATH=$PWD/../custom-devices/devices/${{ matrix.device }}" >> $GITHUB_ENV

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          # Add custom-devices feed
          echo "src-link custom $GITHUB_WORKSPACE/custom-devices" >> feeds.conf.default
          
          # Update feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy device files
        working-directory: ./openwrt
        run: |
          # Copy DTS
          if [ -d "$DEVICE_PATH/target/linux/ramips/dts" ]; then
            cp -r $DEVICE_PATH/target/linux/ramips/dts/* target/linux/ramips/dts/
          fi
          
          # Add device definition to rt305x.mk
          if [ -f "$DEVICE_PATH/target/linux/ramips/image/hiker.mk" ]; then
            cat $DEVICE_PATH/target/linux/ramips/image/hiker.mk >> target/linux/ramips/image/rt305x.mk
          fi

      - name: Load configuration
        working-directory: ./openwrt
        run: |
          # Copy defconfig
          cp $DEVICE_PATH/profiles/${{ matrix.profile }}/defconfig .config
          
          # Copy files overlay
          if [ -d "$DEVICE_PATH/profiles/${{ matrix.profile }}/files" ]; then
            cp -r $DEVICE_PATH/profiles/${{ matrix.profile }}/files .
          fi
          
          # Apply config
          make defconfig

      - name: Download packages
        working-directory: ./openwrt
        run: |
          make download -j$(nproc) || make download -j1 V=s
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        working-directory: ./openwrt
        run: |
          echo "Compiling with $(nproc) threads"
          make -j$(nproc) || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
        id: compile

      - name: Check disk space
        if: (!cancelled())
        run: df -hT

      - name: Organize files
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          
          # Get OpenWrt version
          OPENWRT_VER=$(cat ../../../include/version.mk | grep RELEASE | head -1 | cut -d'=' -f2 | tr -d ' "')
          echo "OPENWRT_VERSION=$OPENWRT_VER" >> $GITHUB_ENV
          
          # Get build date
          BUILD_DATE=$(date +"%Y%m%d")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          
          # Rename firmware
          FIRMWARE_NAME="${{ matrix.device }}-${OPENWRT_VER}-${{ matrix.profile }}"
          echo "FIRMWARE_NAME=$FIRMWARE_NAME" >> $GITHUB_ENV
          
          # Find and rename sysupgrade image
          SYSUPGRADE=$(ls *sysupgrade.bin 2>/dev/null | head -1)
          if [ -n "$SYSUPGRADE" ]; then
            cp "$SYSUPGRADE" "${FIRMWARE_NAME}.bin"
            sha256sum "${FIRMWARE_NAME}.bin" | awk '{print $1 "  " $2}' > "${FIRMWARE_NAME}.bin.sha256"
          fi
          
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV

      - name: Upload firmware directory
        uses: actions/upload-artifact@v4
        if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
        with:
          name: ${{ env.FIRMWARE_NAME }}
          path: ${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE_NAME }}.bin*

      - name: Generate release info
        if: steps.compile.outputs.status == 'success' && github.event.inputs.release == 'true'
        run: |
          cd ${{ env.FIRMWARE_PATH }}
          
          cat > release-${{ matrix.device }}-${{ matrix.profile }}.txt << EOF
          ## ${{ matrix.name }}
          
          **固件信息**
          - 设备: ${{ matrix.device }}
          - 配置: ${{ matrix.profile }}
          - OpenWrt 版本: ${{ env.OPENWRT_VERSION }}
          - 编译日期: ${{ env.BUILD_DATE }}
          - 固件大小: $(ls -lh ${{ env.FIRMWARE_NAME }}.bin | awk '{print $5}')
          
          **SHA256**
          \`\`\`
          $(cat ${{ env.FIRMWARE_NAME }}.bin.sha256)
          \`\`\`
          
          **刷机方法**
          \`\`\`bash
          scp ${{ env.FIRMWARE_NAME }}.bin root@192.168.1.1:/tmp/sysupgrade.bin
          ssh root@192.168.1.1 "sysupgrade -v /tmp/sysupgrade.bin"
          \`\`\`
          EOF

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: steps.compile.outputs.status == 'success' && github.event.inputs.release == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.OPENWRT_VERSION }}-${{ env.BUILD_DATE }}
          name: Release ${{ env.OPENWRT_VERSION }} (${{ env.BUILD_DATE }})
          body_path: ${{ env.FIRMWARE_PATH }}/release-${{ matrix.device }}-${{ matrix.profile }}.txt
          files: |
            ${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE_NAME }}.bin
            ${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE_NAME }}.bin.sha256

