name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  build-all:
    runs-on: ubuntu-24.04
    
    strategy:
      fail-fast: false
      matrix:
        device:
          - hiker-rt5350
        profile:
          - minimal
          - p910nd
          - wifi-client
          - full-wifi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean
          df -h

      - name: Initialize environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget \
            python3 libelf-dev ca-certificates curl

      - name: Clone OpenWrt
        run: |
          git clone --depth 1 https://github.com/openwrt/openwrt.git
          cd openwrt
          echo "src-link custom $GITHUB_WORKSPACE" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure & Build
        run: |
          cd openwrt
          
          # Copy device files
          cp -r ../devices/${{ matrix.device }}/target/linux/ramips/dts/* target/linux/ramips/dts/ || true
          cat ../devices/${{ matrix.device }}/target/linux/ramips/image/*.mk >> target/linux/ramips/image/rt305x.mk || true
          
          # Load config
          cp ../devices/${{ matrix.device }}/profiles/${{ matrix.profile }}/defconfig .config
          cp -r ../devices/${{ matrix.device }}/profiles/${{ matrix.profile }}/files . || true
          make defconfig
          
          # Download & compile
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Organize & Upload
        run: |
          cd openwrt/bin/targets/*/*
          
          # Get version
          OPENWRT_VER=$(cat ../../../include/version.mk | grep RELEASE | head -1 | cut -d'=' -f2 | tr -d ' "')
          DATE=$(date +"%Y%m%d")
          
          # Rename
          FIRMWARE="${{ matrix.device }}-${OPENWRT_VER}-${{ matrix.profile }}"
          SYSUPGRADE=$(ls *sysupgrade.bin | head -1)
          cp "$SYSUPGRADE" "${FIRMWARE}.bin"
          sha256sum "${FIRMWARE}.bin" > "${FIRMWARE}.bin.sha256"
          
          # Save paths
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
          echo "FIRMWARE_NAME=$FIRMWARE" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FIRMWARE_NAME }}
          path: |
            ${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE_NAME }}.bin
            ${{ env.FIRMWARE_PATH }}/${{ env.FIRMWARE_NAME }}.bin.sha256

  create-release:
    needs: build-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-files

      - name: Generate release notes
        run: |
          cat > RELEASE.md << 'EOF'
          # Custom Devices Feed Release
          
          ## 支持的设备
          
          ### Hiker RT5350
          
          | 配置 | 功能 | 推荐 |
          |------|------|------|
          | minimal | 基础系统 | 开发用 |
          | p910nd | USB 打印服务器 | ⭐ 推荐 |
          | wifi-client | 打印 + WiFi 客户端 | 一般 |
          | full-wifi | 完整 WiFi | 不推荐 |
          
          ## 刷机方法
          
          ```bash
          # 1. 上传固件到设备
          scp <firmware>.bin root@192.168.1.1:/tmp/sysupgrade.bin
          
          # 2. SSH 登录设备
          ssh root@192.168.1.1
          
          # 3. 执行升级
          sysupgrade -v /tmp/sysupgrade.bin
          ```
          
          ## SHA256 校验
          
          所有固件包含 `.sha256` 文件，请验证后再刷入。
          
          EOF

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: Release ${{ github.event.inputs.tag || github.ref_name }}
          body_path: RELEASE.md
          draft: false
          prerelease: false
          files: release-files/**/*.bin*

